---
- name: sleep for a specified interval
  command: sleep 60

- name: Install PostgreSQL
  apt:
    name: ['postgresql' , 'python-psycopg2']
    state: latest
  tags:
    - db

- name: Install UFW Firewall
  apt:
    name: 'ufw'
    state: latest
  tags:
    - db

- name: Add ssh service to firewall
  shell: ufw allow ssh

- name: Add postgresql service to firewall
  shell: ufw allow postgresql

- name: Enable the UFW firewall
  ufw:
    state: enabled

- name: Uncomment listen addresses configuration
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: '^#listen_addresses'
    replace: listen_addresses
  notify:
    - restart postgresql
  tags:
    - db

- name: Replace listen addresses
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^listen_addresses\\s+=\\s+'(.*)'"
    replace: "listen_addresses = '{{ addresses }}'"
  notify:
    - restart postgresql
  when: addresses is defined
  tags:
    - db

- name: Add pg_hba.conf line to permit access from network
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ version }}/main/pg_hba.conf"
  notify:
    - restart postgresql
  when: addresses is defined
  tags:
    - db

- name: Ensure service is enabled and started
  service:
    name: postgresql
    state: restarted
    enabled: yes
  tags:
    - db
