- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: europe-west1-b
        gcp_region: europe-west1
        gcp_project: helpful-range-257511
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_machine_type: f1-micro
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20191113
        disk_size: 20
        disks:
          - disk-01
          - disk-02
          - disk-03
        addresses:
          - addr-01
          - addr-02
          - addr-03
        instances:
          - { index: 1, tag: app }
          - { index: 2, tag: database }
          - { index: 3, tag: lb }
