- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: europe-west1-b
        gcp_region: europe-west1
        gcp_project: helpful-range-257511
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_machine_type: n1-standard-1
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20191113
        disk_size: 20
        disks:
          - disk-01
          - disk-02
          - disk-03
          - disk-04
          - disk-05
          - disk-06
          - disk-07
        addresses:
          - addr-01
          - addr-02
          - addr-03
          - addr-04
          - addr-05
          - addr-06
          - addr-07
        instances:
          - { index: 1, tag: django-1 }
          - { index: 2, tag: django-2 }
          - { index: 3, tag: tornado }
          - { index: 4, tag: database-1 }
          - { index: 5, tag: database-2 }
          - { index: 6, tag: nginx-1 }
          - { index: 7, tag: nginx-2 }
- hosts: tornado
  become: yes
  gather_facts: no
  roles:
    - role: zulip
- hosts: database-1:database-2
  become: yes
  gather_facts: no
  roles:
    - role: postgres
