- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: europe-west1-b
        gcp_region: europe-west1
        gcp_project: helpful-range-257511
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_machine_type: n1-standard-1
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20191113
        disk_size: 20
        disks:
          - disk-01
          - disk-02
          - disk-03
          - disk-04
          - disk-05
          - disk-06
        addresses:
          - addr-01
          - addr-02
          - addr-03
          - addr-04
          - addr-05
          - addr-06
        instances:
          - { index: 1, tag: django1 }
          - { index: 2, tag: tornado }
          - { index: 3, tag: database1 }
          - { index: 4, tag: database2 }
          - { index: 5, tag: nginx1 }
          - { index: 6, tag: redis }

- hosts: all
  become: yes
  roles:
    - { role: users, payload: users.yml }

- hosts: database*
  become: yes
  roles:
    - { role: db-postgresql, addresses: '*', version: '9.5' }
    - { role: postgresql-db, dbname: 'zulip' }
    - {
      role: postgresql-user,
      username: 'zulip',
      password: 'zulippass', #"{{ lookup('passwordstore','ansible/uc/db create=true length=8') }}",
      dbname: 'zulip'
      }

- hosts: redis
  become: yes
  roles:
    - {role: redis,
      ipv4_addr: 127.0.0.1,
      redis_user: redis,
      redis_group: redis,
      redis_bind_addr: 0.0.0.0,
      redis_port: 6379,
      redis_tcp_sockets: 511,
      redis_socket: /var/run/redis/redis.sock,
      redis_socket_permissions: 770,
      redis_logfile: /var/log/redis/redis-server.log
      }

- hosts: tornado
  become: yes
  roles:
    - { role: zulip, addresses: addr-03 }

- hosts: nginx*
  become: yes
  roles:
    - web-nginx
    - {
      role: nginx-vhost,
      template: uwsgi-vhost,
      fqdn: uc.lsd.di.uminho.pt,
      root: /srv/apps,
      backend_addresses: "{{ groups['tornado']  }}",
      backend_port: 5000
      }
