- name: GCP Teardown
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gcp_zone: europe-west1-b
    gcp_region: europe-west1
    gcp_project: helpful-range-257511
    gcp_cred_kind: serviceaccount
    gcp_cred_file: credentials.json
  tasks:
    # - name: Debug
    #   debug:
    #     msg: "{{ hostvars[item] }}"
    #   loop: "{{ groups['all'] }}"

    - name: Teardown instances
      gcp_compute_instance:
        name: "{{ hostvars[item].name }}"
        zone: "{{ hostvars[item].zone }}"
        project: "{{ hostvars[item].project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent
      loop: "{{ groups['all'] }}"

    - name: Teardown addresses
      gcp_compute_address:
        name: "{{ item }}"
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent
      loop:
        - addr-01
        - addr-02
        - addr-03
        - addr-04
