- name: Test
  file:
      path: "/home/'{{ addresses }}'.txt"
      state: touch
- name: Download zulip
  shell: cd /home && wget https://www.zulip.org/dist/releases/zulip-server-latest.tar.gz && tar -xf zulip-server-latest.tar.gz
- name: Install zulip
  shell: cd /home && ./zulip-server-*/scripts/setup/install --self-signed-cert --email=diogofiliperfbraga@gmail.com --hostname="{{ addr-03 }}"
