
- name: Uncomment and change Wal Level
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#wal_level = minimal"
    replace: "wal_level = hot_standby"
  notify:
    - restart postgresql
  tags:
    - db

- name: Uncomment and change Synchronous Commit
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#synchronous_commit = on"
    replace: "synchronous_commit = local"
  notify:
    - restart postgresql
  tags:
    - db

- name: Uncomment and change Max Wal Senders
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#max_wal_senders = 0"
    replace: "max_wal_senders = 2"
  notify:
    - restart postgresql
  tags:
    - db

- name: Uncomment and change Wal Keep Segments
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#wal_keep_segments = 0"
    replace: "wal_keep_segments = 10"
  notify:
    - restart postgresql
  tags:
    - db

- name: Uncomment and change Synchronous Standby Names
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#synchronous_standby_names = ''"
    replace: "synchronous_standby_names = 'pgslave001'"
  notify:
    - restart postgresql
  tags:
    - db

- name: Uncomment and change Hot Standby
  replace:
    path: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#hot_standby = off"
    replace: "hot_standby = on"
  notify:
    - restart postgresql
  tags:
    - db
