---

- name: Add repository key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
  tags:
    - web

- name: Add nginx repository
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx
  tags:
    - web

- name: Install nginx
  apt:
    name: nginx
    state: latest
  tags:
    - web

- name: Remove base install configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  tags:
    - web

- name: Create virtual hosts folder
  file:
    path: /etc/nginx/vhosts
    state: directory
  tags:
    - web

- name: Copy configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - web

- name: Enable nginx service
  service:
    name: nginx
    enabled: true
  tags:
    - web
